### ISSUE TITLE
Dataset is not available

### ISSUE THREAD

**Issue by Fazlik995** [yuxiaochen1103/DG-STA#2]
I can't download the datasets.

Web-site is not working.

Could you provide another link to download the datasets, please, or could you solve this problem?

Thank you!

**Comment by yuxiaochen1103** [comment]
Hi,

The provided links are for the official websites of datasets, but the websites can be accessed now. You should contact the owners of the datasets for help, because I do not have the right to share their datasets with you.

**Comment by Fazlik995** [comment]
ok, thank u
