### ISSUE TITLE
Higher accuracy than paper

### ISSUE THREAD

**Issue by Fazlik995** [yuxiaochen1103/DG-STA#4]
Hi,

I followed all requirements you mentioned.

However, when I trained DHG-14 dataset i got accuracy higher than 95% and for DHG-28 90.71%.

These results are too high compare to paper's result.

What is wrong?

Thank you

**Comment by Fridaycoder** [comment]
How about SHREC? I got lower accuracy than the paper.

**Comment by Fazlik995** [comment]
Did you choose the best accuracy?

**Comment by Grant2Grant** [comment]
Maybe you test on only one sequence, while the author reported the result obtained by k-fold cross-validation in the parper.

**Comment by Fazlik995** [comment]
@frspring I follow the structure which author mentioned.
I run python train_on_DHC.py and my best accuracy results was higher.
Maybe, you are right, I need to get k-fold cross validation. I do not understand how to get it now.
Anyway, I will try it again.

**Comment by Fazlik995** [comment]
@frspring Thank you.
You were right. 
Now, after checking results for k-fold cross validation I got close result which was in the paper.
