### ISSUE TITLE
the relationship of joints for DHG dataset

### ISSUE THREAD

**Issue by DianYe2333** [yuxiaochen1103/DG-STA#6]
Hi,thanks for your contribution.
i want to know the relationship of joint point for DHG dataset.In other words,the Link matrix of the 22 joints.
thanks.

**Comment by yuxiaochen1103** [comment]
In my method, the link matrix  is learned by the self-attention mechanism.  If you ask for the relationship between joint id and joint, it shown as following.

wrist = [0]
palm = [1]
thumb = [2,3,4,5]
fore_finger = [6, 7, 8, 9]
middle_finger = [10, 11, 12, 13]
ring_finger = [14, 15, 16, 17]
little_finger = [18, 19, 20, 21]
